Repository jenkinsci/lib-task-reactor, pull requests merged in 2021-11, with the labels that each got.

#6 [SECURITY] Use HTTPS to resolve dependencies in Maven Build
  pom.xml
Labels: maintenance

#8 setup dependabot, release drafter and simplify Jenkinsfile
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  Jenkinsfile
Labels: maintenance

#13 Add missing `@Override` annotations
  src/main/java/org/jvnet/hudson/reactor/Executable.java
  src/main/java/org/jvnet/hudson/reactor/MilestoneImpl.java
  src/main/java/org/jvnet/hudson/reactor/Reactor.java
  src/main/java/org/jvnet/hudson/reactor/ReactorListener.java
  src/main/java/org/jvnet/hudson/reactor/TaskBuilder.java
  src/main/java/org/jvnet/hudson/reactor/TaskGraphBuilder.java
  src/test/java/org/jvnet/hudson/reactor/SessionTest.java
Labels: internal

#14 Update `pom.xml`
  pom.xml
  src/test/java/org/jvnet/hudson/reactor/SessionTest.java
Labels: dependencies

#15 Fix IntelliJ warnings
  src/main/java/org/jvnet/hudson/reactor/ReactorListener.java
  src/test/java/org/jvnet/hudson/reactor/SessionTest.java
Labels: test

#16 Incrementalify
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: internal

#17 Bump Commons IO from 2.7 to 2.11.0
  pom.xml
Labels: dependencies
